FROM ubuntu

# COPY fun1.sh ./fun1.sh
# RUN chmod 777 fun1.sh
# CMD [ "bash","/fun1.sh" ]
# --------------
# COPY fun1.sh ./fun1.sh
# COPY fun2.sh ./fun2.sh
# RUN chmod 777 fun1.sh
# RUN chmod 777 fun2.sh
# CMD [ "bash","/fun1.sh" ]
# ENTRYPOINT  [ "bash","/fun2.sh" ]

# ----------
# ENTRYPOINT  [ "bash" ]
# CMD [ "/fun2.sh" ]    
# ----------
# COPY fun1.sh ./fun1.sh
# COPY fun2.sh ./fun2.sh
# RUN chmod 777 fun1.sh
# RUN chmod 777 fun2.sh
# # -------
# CMD [ "bash","/fun1.sh" ]
# CMD [ "echo","HEllo" ]
# # --------
# ENTRYPOINT [ "echo" ]
# CMD [ "HEllo" ]


# CMD [ "bash","/fun1.sh" ]
# CMD [ "echo","HEllo" ]
# ENTRYPOINT [ "echo" ]
# CMD [ "HEllo" ]

# CMD [ "sleep" , "8" ]
# CMD [ "dddddddd"  ]
# ENTRYPOINT [ "echo" ]



