# version: "3"
# services:
#   nginx:
#     image: nginx
#     container_name: nginx
#     networks:
#       - de
#     volumes:
#       - nginx:/usr/share/nginx/html
#     ports:
#       - "5050:80"  
# networks:
#   de:
#     driver: bridge
# volumes:
#   nginx:
# ------------------------
version: "3"

services:
  appfffff:
    build: .         # This tells Compose to build using Dockerfile in the current dir
    container_name: my-nginx-app
    ports:
      - "5050:80"      

